language: php

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq

install:
  - composer remove --no-update --no-scripts --dev andreaskasper/phlibs
  - composer install
  
script: ./vendor/bin/phpunit --configuration ./travis.phpunit.xml.dist
  
stages:
  - coding-standard
  - test

jobs:
  include:
    - stage: coding-standard
      before_install:
      before_script:
      after_script:
      php: 5.5
      env: CS_CHECK=1
    - stage: test
      php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
      dist: trusty
